//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/Action.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Action : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Action()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Action"",
    ""maps"": [
        {
            ""name"": ""fpsMap"",
            ""id"": ""61f3820e-e096-4885-bfad-a77d4ace073f"",
            ""actions"": [
                {
                    ""name"": ""MoveCamera"",
                    ""type"": ""PassThrough"",
                    ""id"": ""020aebfa-09e9-4835-94be-cd9d69ae09c3"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""435330ed-a558-4dd9-9f10-867216ed171c"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // fpsMap
        m_fpsMap = asset.FindActionMap("fpsMap", throwIfNotFound: true);
        m_fpsMap_MoveCamera = m_fpsMap.FindAction("MoveCamera", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // fpsMap
    private readonly InputActionMap m_fpsMap;
    private IFpsMapActions m_FpsMapActionsCallbackInterface;
    private readonly InputAction m_fpsMap_MoveCamera;
    public struct FpsMapActions
    {
        private @Action m_Wrapper;
        public FpsMapActions(@Action wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveCamera => m_Wrapper.m_fpsMap_MoveCamera;
        public InputActionMap Get() { return m_Wrapper.m_fpsMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(FpsMapActions set) { return set.Get(); }
        public void SetCallbacks(IFpsMapActions instance)
        {
            if (m_Wrapper.m_FpsMapActionsCallbackInterface != null)
            {
                @MoveCamera.started -= m_Wrapper.m_FpsMapActionsCallbackInterface.OnMoveCamera;
                @MoveCamera.performed -= m_Wrapper.m_FpsMapActionsCallbackInterface.OnMoveCamera;
                @MoveCamera.canceled -= m_Wrapper.m_FpsMapActionsCallbackInterface.OnMoveCamera;
            }
            m_Wrapper.m_FpsMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MoveCamera.started += instance.OnMoveCamera;
                @MoveCamera.performed += instance.OnMoveCamera;
                @MoveCamera.canceled += instance.OnMoveCamera;
            }
        }
    }
    public FpsMapActions @fpsMap => new FpsMapActions(this);
    public interface IFpsMapActions
    {
        void OnMoveCamera(InputAction.CallbackContext context);
    }
}
