---
title: "Distribuciones de Probabilidad"
output: html_notebook
---

##### *Execute: Ctrl+Shift+Enter*.

##### *New chunk: Ctrl+Alt+I*.

##### *Preview: Ctrl+Shift+K*.

------------------------------------------------------------------------

-   **fmp**: Funcion de masa de probabilidad.

-   **fd**: Funcion de distribucion.

-   **E(x)**: Valor esperado

-   **Var(x)**: Varianza

------------------------------------------------------------------------

# Distribuciones Discretas

------------------------------------------------------------------------

### Distribucion Bernoulli

Dos posibles resultados en un experimento.

Siendo $p$ la probabilidad del primer evento. Y $q = 1 - p$ la probabilidad del segundo.

$$FMP:\quad f(x) = p^x(1-p)^{1-x};\quad x = 0, 1$$

$$Var(x) = p(1 - p)$$

$$E(x) = p$$

Suponga que una pregunta en un examen de opción múltiple tiene 4 opciones de respuesta de las cuales solamente una es correcta.

Suponga además que un estudiante responde la pregunta seleccionando una de las respuestas al azar.

Sea X la variable aleatoria definida por

$$\{0: No\quad acierta; \quad\quad 1: Si\quad acierta\}$$

```{r echo=TRUE, paged.print=FALSE}

fmp <- function(x){
  0.25^x * 0.75^(1 - x)
}
fmp
cat("Valor esperado: E(x) = 0.25\n")
cat("Varianza: Var(x) = 0.25(1 - 0.25) =", 0.25*(1 - 0.25))
```

### Distribucion Binomial

Dados *n* 

### Distribucion Hipergeométrica

### Distribucion Poisson

### Distribucion Geométrica

# Distribuciones Continuas

### Distribucion Uniforme

### Distribucion Exponencial

### Distribucion Normal

#### Distribucion Normal Estandar

### Distribucion Ji Cuadrada

### Distribucion t-student

### Distribucion F

### Distribucion Weibull


